import { test } from "node:test";
import assert from "node:assert/strict";

import {
  ALWAYS_ABSTAIN,
  SAFETY_PRECISION_THRESHOLD,
  MIN_EVALUATION_SAMPLES,
  REJECT_PRECISION_FLOOR,
  createModelSelector,
  decide,
  evaluateSelector,
  generateCandidates,
  parseSelection,
  type AmbiguousEditCase,
} from "./edit-selection.ts";
import type { ModelClient } from "./runner.ts";

function contentWith(occurrences: number, needle: string, expectedIndent = "  "): { content: string; oldText: string } {
  const lines: string[] = [];
  for (let i = 0; i < occurrences; i++) {
    lines.push(`function before${i}() {`);
    lines.push(`${expectedIndent}return "${needle}";`);
    lines.push("}");
  }
  return { content: `${lines.join("\n")}\n`, oldText: `return "${needle}";` };
}

function fixture(occurrences: number, expectedOrdinal: number, id: string, indent = "  "): AmbiguousEditCase {
  const { content, oldText } = contentWith(occurrences, needleFor(occurrences, id), indent);
  return { caseId: id, content, oldText, expectedOrdinal, candidates: generateCandidates(content, oldText) };
}

function needleFor(occurrences: number, id: string): string {
  return `marker-${occurrences}-${id}`;
}

test("predeclared safety constants are fixed before evaluation", () => {
  assert.equal(SAFETY_PRECISION_THRESHOLD, 0.99);
  assert.equal(MIN_EVALUATION_SAMPLES, 30);
  assert.equal(REJECT_PRECISION_FLOOR, 0.5);
});

test("candidate generator is deterministic and finds exact occurrences in document order", () => {
  const { content, oldText } = contentWith(3, "alpha");
  const first = generateCandidates(content, oldText);
  const second = generateCandidates(content, oldText);
  assert.deepEqual(first, second);
  assert.equal(first.length, 3);
  assert.deepEqual(first.map((c) => c.ordinal), [1, 2, 3]);
  const offsets = first.map((c) => c.offset);
  assert.deepEqual(offsets, [...offsets].sort((a, b) => a - b));
  for (const candidate of first) {
    assert.equal(content.slice(candidate.offset, candidate.offset + candidate.length), oldText);
  }
});

test("generator captures candidate indentation as the only selection signal", () => {
  const { content, oldText } = contentWith(2, "beta", "    ");
  const candidates = generateCandidates(content, oldText);
  assert.ok(candidates.every((c) => c.indent === "    "));
});

test("selection schema permits only a known ordinal or abstain", () => {
  assert.deepEqual(parseSelection(JSON.stringify({ ordinal: 2 }), 3), { selection: { ordinal: 2 }, schemaViolation: false });
  assert.deepEqual(parseSelection(JSON.stringify({ abstain: true }), 3), { selection: { abstain: true }, schemaViolation: false });
  assert.equal(parseSelection(JSON.stringify({ ordinal: 4 }), 3).schemaViolation, true);
  assert.equal(parseSelection(JSON.stringify({ ordinal: 0 }), 3).schemaViolation, true);
  assert.equal(parseSelection("not json", 3).schemaViolation, true);
});

test("content and path generation attempts are refused and flagged as violations", () => {
  for (const field of ["oldText", "newText", "path", "content", "command"]) {
    const parsed = parseSelection(JSON.stringify({ [field]: "generated bytes" }), 3);
    assert.ok("abstain" in parsed.selection, field);
    assert.equal(parsed.schemaViolation, true, field);
  }
});

test("wrong candidate selection is a hard safety failure", async () => {
  const cases = [fixture(3, 1, "c1")];
  const wrong: ModelClient = {
    async complete() {
      return { content: JSON.stringify({ ordinal: 2 }), tokens: 5, latencyMs: 1 };
    },
  };
  const result = await evaluateSelector(cases, createModelSelector(wrong));
  assert.equal(result.wrong, 1);
  assert.equal(result.correct, 0);
  assert.equal(result.precision, 0);
});

test("always-abstain baseline never selects and never errs", async () => {
  const cases = [fixture(3, 1, "c1"), fixture(4, 2, "c2")];
  const result = await evaluateSelector(cases, ALWAYS_ABSTAIN);
  assert.equal(result.selected, 0);
  assert.equal(result.abstentionRate, 1);
  assert.equal(result.wrong, 0);
  assert.equal(result.precision, 0);
  assert.equal(result.coverage, 0);
});

test("model selector reports precision, coverage, abstention, latency, tokens, and cost", async () => {
  const cases = [fixture(3, 1, "c1"), fixture(4, 2, "c2"), fixture(2, 1, "c3")];
  let call = 0;
  const mixed: ModelClient = {
    async complete() {
      call++;
      if (call === 1) return { content: JSON.stringify({ ordinal: 1 }), tokens: 10, latencyMs: 4 }; // correct
      if (call === 2) return { content: JSON.stringify({ ordinal: 3 }), tokens: 12, latencyMs: 6 }; // wrong
      return { content: JSON.stringify({ abstain: true }), tokens: 8, latencyMs: 2 }; // abstain
    },
  };
  const result = await evaluateSelector(cases, createModelSelector(mixed));
  assert.equal(result.total, 3);
  assert.equal(result.selected, 2);
  assert.equal(result.correct, 1);
  assert.equal(result.wrong, 1);
  assert.equal(result.abstained, 1);
  assert.equal(result.precision, 0.5);
  assert.ok(Math.abs(result.coverage - 2 / 3) < 1e-9);
  assert.ok(Math.abs(result.abstentionRate - 1 / 3) < 1e-9);
  assert.equal(result.latencyMs, 12);
  assert.equal(result.tokens, 30);
  assert.equal(result.costUsd, 0.03);
  assert.equal(result.schemaViolations, 0);
});

test("schema-violating outputs count as abstention and are flagged", async () => {
  const cases = [fixture(3, 1, "c1")];
  const violator: ModelClient = {
    async complete() {
      return { content: JSON.stringify({ oldText: "let me write bytes" }), tokens: 7, latencyMs: 1 };
    },
  };
  const result = await evaluateSelector(cases, createModelSelector(violator));
  assert.equal(result.abstained, 1);
  assert.equal(result.schemaViolations, 1);
  assert.equal(result.wrong, 0);
});

function manyCases(count: number, expectedOrdinal: number): AmbiguousEditCase[] {
  return Array.from({ length: count }, (_, i) => fixture(3, expectedOrdinal, `bulk-${i}`));
}

test("decision requires threshold and sample minimum for promotion", async () => {
  const perfect: ModelClient = {
    async complete() {
      return { content: JSON.stringify({ ordinal: 1 }), tokens: 5, latencyMs: 1 };
    },
  };
  const few = await evaluateSelector(manyCases(10, 1), createModelSelector(perfect));
  const fewDecision = decide([few], 10);
  assert.equal(fewDecision.decision, "advisory");
  assert.match(fewDecision.reason, /insufficient-samples/);

  const plenty = await evaluateSelector(manyCases(MIN_EVALUATION_SAMPLES, 1), createModelSelector(perfect));
  assert.equal(decide([plenty], MIN_EVALUATION_SAMPLES).decision, "promote");

  // Alternating correct/wrong ordinal among 3 candidates -> precision 0.5:
  // above the reject floor, below the safety threshold -> advisory.
  let toggle = 0;
  const alternating: ModelClient = {
    async complete() {
      toggle++;
      return { content: JSON.stringify({ ordinal: toggle % 2 === 0 ? 2 : 1 }), tokens: 5, latencyMs: 1 };
    },
  };
  const mixed = await evaluateSelector(manyCases(MIN_EVALUATION_SAMPLES, 1), createModelSelector(alternating));
  assert.ok(Math.abs(mixed.precision - 0.5) < 1e-9);
  assert.equal(decide([mixed], MIN_EVALUATION_SAMPLES).decision, "advisory");
});

test("decide rejects precision below the safety floor", async () => {
  const alwaysWrong: ModelClient = {
    async complete() {
      return { content: JSON.stringify({ ordinal: 2 }), tokens: 5, latencyMs: 1 };
    },
  };
  const result = await evaluateSelector(manyCases(MIN_EVALUATION_SAMPLES, 1), createModelSelector(alwaysWrong));
  assert.equal(result.precision, 0);
  assert.equal(decide([result], MIN_EVALUATION_SAMPLES).decision, "reject");
});
